name: Deploy and test pipeline - DEV

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - "notebooks/**"

  pull_request:
    branches:
      - '**'
    paths-ignore:
      - 'notebooks/**'

jobs:
  python_format_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Check formatting
        run: |
          echo "pass"