name: Verify Version Bump

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch-name:
        type: string
        description: "Set the branch name to run on"
        required: true

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v4

      - name: Get PR Version
        id: pr_version
        run: |
          PR_VERSION=$(grep -m 1 '^version' pyproject.toml | tr -d '"' | tr -d "'" | awk '{print $3}')
          echo "version=$PR_VERSION" >> $GITHUB_OUTPUT

      - name: Checkout base Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}

      - name: Get base branch version
        id: base_version
        run: |
          BASE_VERSION=$(grep -m 1 '^version' pyproject.toml | tr -d '"' | tr -d "'" | awk '{print $3}')
          echo "version=$BASE_VERSION" >> $GITHUB_OUTPUT

      - name: Compare Versions
        run: |
          PR_VERSION="${{ steps.pr_version.outputs.version }}"
          BASE_VERSION="${{ steps.base_version.outputs.version }}"
          
          echo "PR Version: $PR_VERSION"
          echo "Base Version: $BASE_VERSION"
          
          if [ "$PR_VERSION" = "$BASE_VERSION" ]; then
            echo "Error: You must bump the version in pyproject.toml before merging."
            exit 1
          fi