name: Verify Version Bump

on:
      
  pull_request:
    branches:
      - main
      - "**"
    paths:
      - "notebooks/**"
      - '.github/workflows/**'

jobs:
  check-version:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }} 
    steps:
      - name: Auto-pass for ignored paths
        run: echo "Only notebooks changed. Instantly passing status check f."