name: Verify Version Bump

on:
      
  pull_request:
    branches:
      - main
    paths-ignore:
      - "notebooks/**" 

  workflow_dispatch:
    inputs:
      branch-name:
        type: string
        description: "Set the branch name to run on"
        required: true

jobs:
  check-version:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }} 
    steps:
      - name: Auto-pass for ignored paths
        run: echo "Only notebooks changed. Instantly passing status check."